server:
  port: 83
spring:
  application:
    name: nacos-order-consumer
  cloud:
    nacos:
      discovery:
        server-addr: nacos:8848


service-url:
  nacos-user-service: http://nacos-payment-provider


management:
  endpoints:
    web:
      exposure:
        include: '*'