server:
  port: 80


spring:
  application:
    name: cloud-order-service


eureka:
  instance:
    instance-id: order80
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka1:7001/eureka/,http://eureka2:7002/eureka/