server:
  port: 8001
spring:
  application:
    name: cloud-payment-service

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://xgsama:3307/cloud?useUnicode=true&characterEncoding-utf-8&useSSL=false
    username: root
    password: cyz19980815


mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka1:7001/eureka/,http://eureka2:7002/eureka/
