server:
  port: 7001

eureka:
  instance:
    hostname: eureka1
  client:
    # 是否向注册中心注册自己
    register-with-eureka: false
    # false表示自己端就是注册中心，职责是维护服务实例，并不需要去检索服务
    fetch-registry: false
    service-url:
      defaultZone: http://eureka1:7001/eureka/
      # 设置与eureka server交互的地址查询服务和注册服务都需要历来这个地址
#      defaultZone: http://eureka2:7002/eureka/
